services:
  frontend:
    image: oven/bun:latest
    platform: linux/arm64
    volumes:
      - ..:/workspace
    expose: ["5173"]

  api:
    image: swift:6.1-jammy
    platform: linux/arm64
    volumes:
      - ..:/workspace
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: vapor_username
      DATABASE_PASSWORD: vapor_password
      DATABASE_NAME: vapor_database
    depends_on: [db]
    expose: ["8080"]

  db:
    image: postgres:16
    platform: linux/arm64
    environment:
      POSTGRES_USER: vapor_username
      POSTGRES_PASSWORD: vapor_password
      POSTGRES_DB: vapor_database
    volumes:
      - postgres_db:/var/lib/postgresql/data
    expose: ["5432"]

volumes:
  postgres_db: