services:
  frontend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.frontend
    platform: linux/arm64
    volumes:
      - cqrs-es-src:/workspace:cached
      - bun-cache:/root/.bun-cache
      - playwright-browsers:/.jbdevcontainer/ms-playwright
    ports:
      - "5173:5173"

  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.api
    platform: linux/arm64
    command: sh -c "cd api && swift run"
    volumes:
      - cqrs-es-src:/workspace:cached
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: vapor_username
      DATABASE_PASSWORD: vapor_password
      DATABASE_NAME: vapor_database
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vapor_username
      POSTGRES_PASSWORD: vapor_password
      POSTGRES_DB: vapor_database
    ports:
      - "5432:5432"

volumes:
  cqrs-es-src:
  bun-cache:
  playwright-browsers:
  pg-data:
