services:
  frontend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.frontend
    platform: linux/arm64
    volumes:
      - ./../:/workspace
    expose: ["5173"]

  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.api
    platform: linux/arm64
    command: sh -c "cd api && swift run"
    volumes:
      - ./../:/workspace
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: vapor_username
      DATABASE_PASSWORD: vapor_password
      DATABASE_NAME: vapor_database
    depends_on: [db]
    expose: ["8080"]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: vapor_username
      POSTGRES_PASSWORD: vapor_password
      POSTGRES_DB: vapor_database
    expose: ["5432"]
